// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package ports

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for InvoiceStatus.
const (
	InvoiceStatusExpired InvoiceStatus = "expired"
	InvoiceStatusPaid    InvoiceStatus = "paid"
	InvoiceStatusPending InvoiceStatus = "pending"
	InvoiceStatusVoided  InvoiceStatus = "voided"
)

// Valid indicates whether the value is a known member of the InvoiceStatus enum.
func (e InvoiceStatus) Valid() bool {
	switch e {
	case InvoiceStatusExpired:
		return true
	case InvoiceStatusPaid:
		return true
	case InvoiceStatusPending:
		return true
	case InvoiceStatusVoided:
		return true
	default:
		return false
	}
}

// Defines values for GetBidderPendingInvoicesParamsStatus.
const (
	GetBidderPendingInvoicesParamsStatusPending GetBidderPendingInvoicesParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the GetBidderPendingInvoicesParamsStatus enum.
func (e GetBidderPendingInvoicesParamsStatus) Valid() bool {
	switch e {
	case GetBidderPendingInvoicesParamsStatusPending:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Slug string `json:"slug"`
}

// Invoice defines model for Invoice.
type Invoice struct {
	// Attempt 1 = original winner, 2 = second chance.
	Attempt         int                `json:"attempt"`
	AuctionId       openapi_types.UUID `json:"auctionId"`
	CommissionMinor int64              `json:"commissionMinor"`
	Currency        string             `json:"currency"`
	DueAt           time.Time          `json:"dueAt"`
	HammerMinor     int64              `json:"hammerMinor"`
	InvoiceId       openapi_types.UUID `json:"invoiceId"`
	Status          InvoiceStatus      `json:"status"`
	TotalMinor      int64              `json:"totalMinor"`
}

// InvoiceStatus defines model for Invoice.Status.
type InvoiceStatus string

// InvoiceList defines model for InvoiceList.
type InvoiceList struct {
	Invoices []Invoice `json:"invoices"`
}

// InvoiceID defines model for invoiceID.
type InvoiceID = openapi_types.UUID

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetBidderPendingInvoicesParams defines parameters for GetBidderPendingInvoices.
type GetBidderPendingInvoicesParams struct {
	// Status Only "pending" is supported.
	Status *GetBidderPendingInvoicesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetBidderPendingInvoicesParamsStatus defines parameters for GetBidderPendingInvoices.
type GetBidderPendingInvoicesParamsStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Pending invoices of the bidder (only their own)
	// (GET /bidders/{bidderID}/invoices)
	GetBidderPendingInvoices(w http.ResponseWriter, r *http.Request, bidderID openapi_types.UUID, params GetBidderPendingInvoicesParams)
	// Invoice details for its debtor
	// (GET /invoices/{invoiceID})
	GetInvoice(w http.ResponseWriter, r *http.Request, invoiceID InvoiceID)
	// Pay the invoice (PSP protocol with refund compensation)
	// (POST /invoices/{invoiceID}/payment)
	PayInvoice(w http.ResponseWriter, r *http.Request, invoiceID InvoiceID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Pending invoices of the bidder (only their own)
// (GET /bidders/{bidderID}/invoices)
func (_ Unimplemented) GetBidderPendingInvoices(w http.ResponseWriter, r *http.Request, bidderID openapi_types.UUID, params GetBidderPendingInvoicesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Invoice details for its debtor
// (GET /invoices/{invoiceID})
func (_ Unimplemented) GetInvoice(w http.ResponseWriter, r *http.Request, invoiceID InvoiceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Pay the invoice (PSP protocol with refund compensation)
// (POST /invoices/{invoiceID}/payment)
func (_ Unimplemented) PayInvoice(w http.ResponseWriter, r *http.Request, invoiceID InvoiceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBidderPendingInvoices operation middleware
func (siw *ServerInterfaceWrapper) GetBidderPendingInvoices(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "bidderID" -------------
	var bidderID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "bidderID", chi.URLParam(r, "bidderID"), &bidderID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bidderID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBidderPendingInvoicesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBidderPendingInvoices(w, r, bidderID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInvoice operation middleware
func (siw *ServerInterfaceWrapper) GetInvoice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "invoiceID" -------------
	var invoiceID InvoiceID

	err = runtime.BindStyledParameterWithOptions("simple", "invoiceID", chi.URLParam(r, "invoiceID"), &invoiceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invoiceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInvoice(w, r, invoiceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PayInvoice operation middleware
func (siw *ServerInterfaceWrapper) PayInvoice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "invoiceID" -------------
	var invoiceID InvoiceID

	err = runtime.BindStyledParameterWithOptions("simple", "invoiceID", chi.URLParam(r, "invoiceID"), &invoiceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invoiceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PayInvoice(w, r, invoiceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bidders/{bidderID}/invoices", wrapper.GetBidderPendingInvoices)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/invoices/{invoiceID}", wrapper.GetInvoice)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/invoices/{invoiceID}/payment", wrapper.PayInvoice)
	})

	return r
}

type GetBidderPendingInvoicesRequestObject struct {
	BidderID openapi_types.UUID `json:"bidderID"`
	Params   GetBidderPendingInvoicesParams
}

type GetBidderPendingInvoicesResponseObject interface {
	VisitGetBidderPendingInvoicesResponse(w http.ResponseWriter) error
}

type GetBidderPendingInvoices200JSONResponse InvoiceList

func (response GetBidderPendingInvoices200JSONResponse) VisitGetBidderPendingInvoicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBidderPendingInvoices400JSONResponse Error

func (response GetBidderPendingInvoices400JSONResponse) VisitGetBidderPendingInvoicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetBidderPendingInvoices403JSONResponse Error

func (response GetBidderPendingInvoices403JSONResponse) VisitGetBidderPendingInvoicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetInvoiceRequestObject struct {
	InvoiceID InvoiceID `json:"invoiceID"`
}

type GetInvoiceResponseObject interface {
	VisitGetInvoiceResponse(w http.ResponseWriter) error
}

type GetInvoice200JSONResponse Invoice

func (response GetInvoice200JSONResponse) VisitGetInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInvoice404JSONResponse Error

func (response GetInvoice404JSONResponse) VisitGetInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PayInvoiceRequestObject struct {
	InvoiceID InvoiceID `json:"invoiceID"`
}

type PayInvoiceResponseObject interface {
	VisitPayInvoiceResponse(w http.ResponseWriter) error
}

type PayInvoice204Response struct {
}

func (response PayInvoice204Response) VisitPayInvoiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PayInvoice404JSONResponse Error

func (response PayInvoice404JSONResponse) VisitPayInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PayInvoice409JSONResponse Error

func (response PayInvoice409JSONResponse) VisitPayInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PayInvoice502JSONResponse Error

func (response PayInvoice502JSONResponse) VisitPayInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Pending invoices of the bidder (only their own)
	// (GET /bidders/{bidderID}/invoices)
	GetBidderPendingInvoices(ctx context.Context, request GetBidderPendingInvoicesRequestObject) (GetBidderPendingInvoicesResponseObject, error)
	// Invoice details for its debtor
	// (GET /invoices/{invoiceID})
	GetInvoice(ctx context.Context, request GetInvoiceRequestObject) (GetInvoiceResponseObject, error)
	// Pay the invoice (PSP protocol with refund compensation)
	// (POST /invoices/{invoiceID}/payment)
	PayInvoice(ctx context.Context, request PayInvoiceRequestObject) (PayInvoiceResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetBidderPendingInvoices operation middleware
func (sh *strictHandler) GetBidderPendingInvoices(w http.ResponseWriter, r *http.Request, bidderID openapi_types.UUID, params GetBidderPendingInvoicesParams) {
	var request GetBidderPendingInvoicesRequestObject

	request.BidderID = bidderID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBidderPendingInvoices(ctx, request.(GetBidderPendingInvoicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBidderPendingInvoices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBidderPendingInvoicesResponseObject); ok {
		if err := validResponse.VisitGetBidderPendingInvoicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInvoice operation middleware
func (sh *strictHandler) GetInvoice(w http.ResponseWriter, r *http.Request, invoiceID InvoiceID) {
	var request GetInvoiceRequestObject

	request.InvoiceID = invoiceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInvoice(ctx, request.(GetInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInvoice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInvoiceResponseObject); ok {
		if err := validResponse.VisitGetInvoiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PayInvoice operation middleware
func (sh *strictHandler) PayInvoice(w http.ResponseWriter, r *http.Request, invoiceID InvoiceID) {
	var request PayInvoiceRequestObject

	request.InvoiceID = invoiceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PayInvoice(ctx, request.(PayInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PayInvoice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PayInvoiceResponseObject); ok {
		if err := validResponse.VisitPayInvoiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFbdbttGE32VwX4fEBmgKMV2ipZALpw4bVQ0rZC46EXoixV3JG5CzjK7SyuEK6AP0XfIe+RR+iTFLEn9",
	"J3DQOuiVSC135syZMz+3IjNlZQjJO5HcikpaWaJHG9403Rid4eSyfRGJqKTPRSRIliiSrfNIWHxXa4tK",
	"JN7WGAmX5VhKvjg3tpReJKKutRKR8E3Fl523mhZitVr1Hwefz6w1NkCxpkLrNYa/XVEv+Hf/8rbj1+1X",
	"12sXZvYGMy9WkZi0SA/tSu+xrDw/KnSZ1ZXXhiN9CI/BWL3QJAtYaiK0EZzCY3CYGVKQ5ZIyjDfxaPK4",
	"QMveZJ2xlYm6Q/gRZ6DUzmlDLzS1sa/vaPLfnB/1kdXWImXNEVIioWq88DuGlPQ49LrEYwhyWZZov8R7",
	"n/m7Rei89HWgG6kuOVEVkuLDSFQy3MH3VUhiJG6MVqi2srix442Xxd1h7oljg3k7Q2t0uzQcpmXH/Rb/",
	"PdvRWkufEeBP2vlDEXbI2mePZXj4v8W5SMT/RpsKHXV1MurlvFp7ktbK5lMhuyOQOC2Y1Vb75hVbbb3P",
	"UFq0F7XPN2/f9zz/+NuV6GqVLbWnG95z76u2nDXNzWFFPdFFoWkBmSGP7z0gqcpo8g4GFy+fPp9cPXt6",
	"9evLZ3Gp4OOHb08S8DmCwpk39oGDLpSUbjQuHUhS4Xz6agqVbEokD5U13mSmgMHHD2fxw5MYLsjrIWsO",
	"rWQUCciU5saiXlBvETQbV9p5TYtau1zOCoS5NSVICAqgBRhC+OuPP2FmfJ6SJLdEC+fj897IkIwfzk1N",
	"KobQwRxIi8D9CDC8JyndpqFBpSKBVMRxnIoVLLXPQyDPr66m0EoRMmltw2754K0mFafEPGtfMNEvTGE8",
	"9HReTCdcNWhd17jiMevCVEiy0iIRZ/E4PguV5vOQ5NFMK4XWjW7bh8nlarQtwQUGjbJCZd/HxA/on4Sv",
	"p23pTvoL0c7QeH10UPR+/tGciPYF9QsVDaR9L0kFZ9LVVWWsR8WdOSB5V6NtNlDW1b5xvN+UDlvP6pqB",
	"u8qQayk6HY/5J0iZAluyqgqdBb5Gbxzju91ycYdiDq0hlM9ulFc5QsvfAwcdxF52LuZUn/+LYNrxewRG",
	"TWtqhy2Hw7kuPNoOwtn9Q+AaM0sa9sGHiuQSYbF1HLEGyPjwdyaLAi0MzJLCJ8PJZQRkYKshgKvtXGZ4",
	"ErcdsS5LaRuRiOke0WDmwWbnZWBYez5HbcEs6YTlKhesfzFr61Jcs8F1XY1u18vS6nM11nf2g6o6xtjm",
	"k9FmFfsaWv2UTjsUnSTO718SB+03aKKmt8RJv/j5Eva6vQNZ6LcIA7k3Gg4U0IUKCr3UhWNDoL3rJtIX",
	"JXzUTagw+Y07sm2e8ihhbM6ARV9bQhU8SgKtsKwMk8hHtmEpSgJZWJSqAV6gUuqZh0fjU6hcNaxJ3khd",
	"hGGmXXuTX5L12MxyaRd8mNKWi1mzGYzd3NkV6VQ29yLS80NWplIrGGjKilr14/AObPQBnPz3ddgh/O5r",
	"IhwWhhZoh5UMgoDf+wVqqDArNPHsXEXi0fj0/lHtK5VZc3KO4E2b3oO+LJtWBp1GB2EB7Be/sE1ZnHMC",
	"GAaSa4v7eLlu7cBBvtvb7+tr1qhDe9OLu7aFSMSIl6rV9ervAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
