// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package ports

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for SettlementFailureReason.
const (
	PaymentTimeout       SettlementFailureReason = "payment_timeout"
	SecondChanceDeclined SettlementFailureReason = "second_chance_declined"
)

// Valid indicates whether the value is a known member of the SettlementFailureReason enum.
func (e SettlementFailureReason) Valid() bool {
	switch e {
	case PaymentTimeout:
		return true
	case SecondChanceDeclined:
		return true
	default:
		return false
	}
}

// Defines values for SettlementState.
const (
	AwaitingPayment     SettlementState = "awaiting_payment"
	AwardingRunnerUp    SettlementState = "awarding_runner_up"
	FailedUnsold        SettlementState = "failed_unsold"
	Relisted            SettlementState = "relisted"
	SecondChancePayment SettlementState = "second_chance_payment"
	Settled             SettlementState = "settled"
	Started             SettlementState = "started"
)

// Valid indicates whether the value is a known member of the SettlementState enum.
func (e SettlementState) Valid() bool {
	switch e {
	case AwaitingPayment:
		return true
	case AwardingRunnerUp:
		return true
	case FailedUnsold:
		return true
	case Relisted:
		return true
	case SecondChancePayment:
		return true
	case Settled:
		return true
	case Started:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Slug string `json:"slug"`
}

// Settlement defines model for Settlement.
type Settlement struct {
	// Attempt 1 = original winner, 2 = second chance.
	Attempt       int                      `json:"attempt"`
	AuctionId     openapi_types.UUID       `json:"auctionId"`
	Currency      string                   `json:"currency"`
	FailureReason *SettlementFailureReason `json:"failureReason,omitempty"`
	HammerMinor   int64                    `json:"hammerMinor"`

	// InvoiceId The invoice the saga currently awaits.
	InvoiceId         *openapi_types.UUID `json:"invoiceId,omitempty"`
	RelistGeneration  int                 `json:"relistGeneration"`
	RunnerUpId        *openapi_types.UUID `json:"runnerUpId,omitempty"`
	RunnerUpMinor     *int64              `json:"runnerUpMinor,omitempty"`
	RunnerUpQualifies bool                `json:"runnerUpQualifies"`
	State             SettlementState     `json:"state"`

	// WinnerId The current debtor (the runner-up after an award).
	WinnerId openapi_types.UUID `json:"winnerId"`
}

// SettlementFailureReason defines model for Settlement.FailureReason.
type SettlementFailureReason string

// SettlementState defines model for Settlement.State.
type SettlementState string

// AuctionID defines model for auctionID.
type AuctionID = openapi_types.UUID

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Decline the second-chance offer (runner-up debtor only)
	// (POST /auctions/{auctionID}/second-chance/decline)
	DeclineSecondChanceOffer(w http.ResponseWriter, r *http.Request, auctionID AuctionID)
	// Settlement saga status (operations role)
	// (GET /auctions/{auctionID}/settlement)
	GetSettlementStatus(w http.ResponseWriter, r *http.Request, auctionID AuctionID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Decline the second-chance offer (runner-up debtor only)
// (POST /auctions/{auctionID}/second-chance/decline)
func (_ Unimplemented) DeclineSecondChanceOffer(w http.ResponseWriter, r *http.Request, auctionID AuctionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Settlement saga status (operations role)
// (GET /auctions/{auctionID}/settlement)
func (_ Unimplemented) GetSettlementStatus(w http.ResponseWriter, r *http.Request, auctionID AuctionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeclineSecondChanceOffer operation middleware
func (siw *ServerInterfaceWrapper) DeclineSecondChanceOffer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "auctionID" -------------
	var auctionID AuctionID

	err = runtime.BindStyledParameterWithOptions("simple", "auctionID", chi.URLParam(r, "auctionID"), &auctionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "auctionID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeclineSecondChanceOffer(w, r, auctionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettlementStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSettlementStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "auctionID" -------------
	var auctionID AuctionID

	err = runtime.BindStyledParameterWithOptions("simple", "auctionID", chi.URLParam(r, "auctionID"), &auctionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "auctionID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettlementStatus(w, r, auctionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auctions/{auctionID}/second-chance/decline", wrapper.DeclineSecondChanceOffer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auctions/{auctionID}/settlement", wrapper.GetSettlementStatus)
	})

	return r
}

type DeclineSecondChanceOfferRequestObject struct {
	AuctionID AuctionID `json:"auctionID"`
}

type DeclineSecondChanceOfferResponseObject interface {
	VisitDeclineSecondChanceOfferResponse(w http.ResponseWriter) error
}

type DeclineSecondChanceOffer204Response struct {
}

func (response DeclineSecondChanceOffer204Response) VisitDeclineSecondChanceOfferResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeclineSecondChanceOffer403JSONResponse Error

func (response DeclineSecondChanceOffer403JSONResponse) VisitDeclineSecondChanceOfferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeclineSecondChanceOffer404JSONResponse Error

func (response DeclineSecondChanceOffer404JSONResponse) VisitDeclineSecondChanceOfferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeclineSecondChanceOffer409JSONResponse Error

func (response DeclineSecondChanceOffer409JSONResponse) VisitDeclineSecondChanceOfferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettlementStatusRequestObject struct {
	AuctionID AuctionID `json:"auctionID"`
}

type GetSettlementStatusResponseObject interface {
	VisitGetSettlementStatusResponse(w http.ResponseWriter) error
}

type GetSettlementStatus200JSONResponse Settlement

func (response GetSettlementStatus200JSONResponse) VisitGetSettlementStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettlementStatus403JSONResponse Error

func (response GetSettlementStatus403JSONResponse) VisitGetSettlementStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettlementStatus404JSONResponse Error

func (response GetSettlementStatus404JSONResponse) VisitGetSettlementStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Decline the second-chance offer (runner-up debtor only)
	// (POST /auctions/{auctionID}/second-chance/decline)
	DeclineSecondChanceOffer(ctx context.Context, request DeclineSecondChanceOfferRequestObject) (DeclineSecondChanceOfferResponseObject, error)
	// Settlement saga status (operations role)
	// (GET /auctions/{auctionID}/settlement)
	GetSettlementStatus(ctx context.Context, request GetSettlementStatusRequestObject) (GetSettlementStatusResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeclineSecondChanceOffer operation middleware
func (sh *strictHandler) DeclineSecondChanceOffer(w http.ResponseWriter, r *http.Request, auctionID AuctionID) {
	var request DeclineSecondChanceOfferRequestObject

	request.AuctionID = auctionID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeclineSecondChanceOffer(ctx, request.(DeclineSecondChanceOfferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeclineSecondChanceOffer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeclineSecondChanceOfferResponseObject); ok {
		if err := validResponse.VisitDeclineSecondChanceOfferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSettlementStatus operation middleware
func (sh *strictHandler) GetSettlementStatus(w http.ResponseWriter, r *http.Request, auctionID AuctionID) {
	var request GetSettlementStatusRequestObject

	request.AuctionID = auctionID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSettlementStatus(ctx, request.(GetSettlementStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSettlementStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSettlementStatusResponseObject); ok {
		if err := validResponse.VisitGetSettlementStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFbvrtPGE32V0f5+UnMlx0khQq0rPiCgQCVUyg3qB3IV7bUn8cJ6150dJ0RRpD5E34H34FH6JNXu2rHD",
	"zVVvJWg/Jfb+mTPnzMzxXuS2qq1Bw05ke1FLkhUyUniSTc7KmhdP/IMyIhO15FIkwsgKRTZYTwThb40i",
	"LETG1GAiXF5iJf3BlaVKsshE06hCJIJ3tT/smJRZi8Ph0G0OMZ8SWQpQyNZIrDC8drpZ+9/PDw8Dv427",
	"ro4h7PU7zFkcEnGJzBorNHzzasmMVR0WCnQ5qdonJTLxLTwES2qtjNSwVcYgJXAPHoLD3JoC8lKaHNM+",
	"JWUY10g+YEdNcQcGEpE3RGjy3ZkME7GSSjeEr1E6D2sv0DSVz7aWO5/RklWFtmGRiAhsGYEtC8y1MlgM",
	"GOlvLWVVIb1UJrJ9hKgMP5idTUmZjVU5xpROmZqXCO0ycIng5FpCTIr1DuRWKnaeqL9lglArx8/QIMl4",
	"+f4MFGq8GG/qO9Lbbf8n2XZnfmmkVqu2VNpt19ZqlMZvcywZh6I4lsToYYSslVkvW53iKyr8q3j7sqlv",
	"iNZvdqFmC9GREv76YsBi2Rhn9XlhY6HeplIrChR4zZZg5NWKYMZNDXLFSCANBKAXd1Dsswbsy76jZgDo",
	"tOgGVX+O7TOlkBxb9WaLHwKPDSneXfphEvW6RklIjxou+6cfu4R++nUu2tETRA2rfYYlcx2nkzIre5PN",
	"fqRAbg3jBwY0RW2VYQejR68fP38xf/p4/ub107Qq4NPH7y4yOGH7G7cwUftx1B7ahoXRp48P0tkFSFOE",
	"I35aBQrc2Bq9i+3l6W3cwmwUblMIY9OBJAQ/BAHDcwb7RRiKC5HBQqRpuhAH2Couw73P5/NXx3tySbRT",
	"Zh1W3itTpAtPOSvWno6XVluGQdKPXr0QidgguXZaplNffrZGI2slMnE/nab3RRI8I6gxaavDTfZH5zhM",
	"TiiYtBSEKW3dmaF8bzoDqZ2F3PrYAa0qsKote1SETDvYltYh2IZzWyFITSiL3cJUkvMSHfz5+x/h3DUa",
	"tTZAMkeQa6mM4/AeP9TK32LpPRIQOqs36IDtwsTpViF430TjgiywsvS+Uy3SdpTMN6J4ErO6DKk+Dpn+",
	"vFqFahs67tu9+D/hSmTif5Pelyf9lknvuIcr3yGutsbFWr83nd1kqw1cwMgSHLF3xGyl68gBQpmX6Hv+",
	"kIjZ9L6/K9R1tExZ11rlIaPJu9aHeos/h7r19Ek09NBIp9iM5bH1LIwJc1UrL1+nTC61RoLCogNjGUqr",
	"YytotUEIp1qgs68P1B2Lfuwxr2xjijb6918/eqSolWlcS1UcWWq9ArbWxNEic/yhlVkjRNwujdOxqSpJ",
	"u74m4r6T+RNCwaj3g9Yl/NC58LNArl3wuP5r6srffVtjD7+51hh+TvviGXI/US7DIPqyLTH9YvoMviDP",
	"iDTvPnqC6f17PfSZM/znPXFSaAOzGDgWjHrQQFbj7ZU1MPVQCUM7f3vl5XZIm65OGtIiExNvPoerw18B",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
