// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package ports

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ProfileResponseStatus.
const (
	Registered ProfileResponseStatus = "registered"
	Verified   ProfileResponseStatus = "verified"
)

// Valid indicates whether the value is a known member of the ProfileResponseStatus enum.
func (e ProfileResponseStatus) Valid() bool {
	switch e {
	case Registered:
		return true
	case Verified:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Slug Stable client-facing error identifier.
	Slug string `json:"slug"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	DisplayName   string                `json:"displayName"`
	Email         string                `json:"email"`
	ParticipantId string                `json:"participantId"`
	Status        ProfileResponseStatus `json:"status"`
}

// ProfileResponseStatus defines model for ProfileResponse.Status.
type ProfileResponseStatus string

// RegisterParticipantRequest defines model for RegisterParticipantRequest.
type RegisterParticipantRequest struct {
	DisplayName string `json:"displayName"`
	Email       string `json:"email"`

	// Id Client-generated participant UUID.
	Id string `json:"id"`
}

// ParticipantID defines model for participantID.
type ParticipantID = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// RegisterParticipantJSONRequestBody defines body for RegisterParticipant for application/json ContentType.
type RegisterParticipantJSONRequestBody = RegisterParticipantRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register a new participant
	// (POST /participants)
	RegisterParticipant(w http.ResponseWriter, r *http.Request)
	// Read a participant profile
	// (GET /participants/{participantID})
	ParticipantProfile(w http.ResponseWriter, r *http.Request, participantID ParticipantID)
	// Verify a participant (operations role)
	// (POST /participants/{participantID}/verification)
	VerifyParticipant(w http.ResponseWriter, r *http.Request, participantID ParticipantID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Register a new participant
// (POST /participants)
func (_ Unimplemented) RegisterParticipant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read a participant profile
// (GET /participants/{participantID})
func (_ Unimplemented) ParticipantProfile(w http.ResponseWriter, r *http.Request, participantID ParticipantID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify a participant (operations role)
// (POST /participants/{participantID}/verification)
func (_ Unimplemented) VerifyParticipant(w http.ResponseWriter, r *http.Request, participantID ParticipantID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RegisterParticipant operation middleware
func (siw *ServerInterfaceWrapper) RegisterParticipant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterParticipant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ParticipantProfile operation middleware
func (siw *ServerInterfaceWrapper) ParticipantProfile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "participantID" -------------
	var participantID ParticipantID

	err = runtime.BindStyledParameterWithOptions("simple", "participantID", chi.URLParam(r, "participantID"), &participantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "participantID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ParticipantProfile(w, r, participantID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyParticipant operation middleware
func (siw *ServerInterfaceWrapper) VerifyParticipant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "participantID" -------------
	var participantID ParticipantID

	err = runtime.BindStyledParameterWithOptions("simple", "participantID", chi.URLParam(r, "participantID"), &participantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "participantID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyParticipant(w, r, participantID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/participants", wrapper.RegisterParticipant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/participants/{participantID}", wrapper.ParticipantProfile)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/participants/{participantID}/verification", wrapper.VerifyParticipant)
	})

	return r
}

type RegisterParticipantRequestObject struct {
	Body *RegisterParticipantJSONRequestBody
}

type RegisterParticipantResponseObject interface {
	VisitRegisterParticipantResponse(w http.ResponseWriter) error
}

type RegisterParticipant204ResponseHeaders struct {
	ContentLocation *string
}

type RegisterParticipant204Response struct {
	Headers RegisterParticipant204ResponseHeaders
}

func (response RegisterParticipant204Response) VisitRegisterParticipantResponse(w http.ResponseWriter) error {
	if response.Headers.ContentLocation != nil {
		w.Header().Set("Content-Location", fmt.Sprint(*response.Headers.ContentLocation))
	}
	w.WriteHeader(204)
	return nil
}

type RegisterParticipant400JSONResponse Error

func (response RegisterParticipant400JSONResponse) VisitRegisterParticipantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterParticipant409JSONResponse Error

func (response RegisterParticipant409JSONResponse) VisitRegisterParticipantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ParticipantProfileRequestObject struct {
	ParticipantID ParticipantID `json:"participantID"`
}

type ParticipantProfileResponseObject interface {
	VisitParticipantProfileResponse(w http.ResponseWriter) error
}

type ParticipantProfile200JSONResponse ProfileResponse

func (response ParticipantProfile200JSONResponse) VisitParticipantProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ParticipantProfile400JSONResponse Error

func (response ParticipantProfile400JSONResponse) VisitParticipantProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ParticipantProfile401JSONResponse Error

func (response ParticipantProfile401JSONResponse) VisitParticipantProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ParticipantProfile404JSONResponse Error

func (response ParticipantProfile404JSONResponse) VisitParticipantProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyParticipantRequestObject struct {
	ParticipantID ParticipantID `json:"participantID"`
}

type VerifyParticipantResponseObject interface {
	VisitVerifyParticipantResponse(w http.ResponseWriter) error
}

type VerifyParticipant204Response struct {
}

func (response VerifyParticipant204Response) VisitVerifyParticipantResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type VerifyParticipant400JSONResponse Error

func (response VerifyParticipant400JSONResponse) VisitVerifyParticipantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyParticipant401JSONResponse Error

func (response VerifyParticipant401JSONResponse) VisitVerifyParticipantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyParticipant403JSONResponse Error

func (response VerifyParticipant403JSONResponse) VisitVerifyParticipantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyParticipant404JSONResponse Error

func (response VerifyParticipant404JSONResponse) VisitVerifyParticipantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyParticipant409JSONResponse Error

func (response VerifyParticipant409JSONResponse) VisitVerifyParticipantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Register a new participant
	// (POST /participants)
	RegisterParticipant(ctx context.Context, request RegisterParticipantRequestObject) (RegisterParticipantResponseObject, error)
	// Read a participant profile
	// (GET /participants/{participantID})
	ParticipantProfile(ctx context.Context, request ParticipantProfileRequestObject) (ParticipantProfileResponseObject, error)
	// Verify a participant (operations role)
	// (POST /participants/{participantID}/verification)
	VerifyParticipant(ctx context.Context, request VerifyParticipantRequestObject) (VerifyParticipantResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RegisterParticipant operation middleware
func (sh *strictHandler) RegisterParticipant(w http.ResponseWriter, r *http.Request) {
	var request RegisterParticipantRequestObject

	var body RegisterParticipantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterParticipant(ctx, request.(RegisterParticipantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterParticipant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterParticipantResponseObject); ok {
		if err := validResponse.VisitRegisterParticipantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ParticipantProfile operation middleware
func (sh *strictHandler) ParticipantProfile(w http.ResponseWriter, r *http.Request, participantID ParticipantID) {
	var request ParticipantProfileRequestObject

	request.ParticipantID = participantID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ParticipantProfile(ctx, request.(ParticipantProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ParticipantProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ParticipantProfileResponseObject); ok {
		if err := validResponse.VisitParticipantProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyParticipant operation middleware
func (sh *strictHandler) VerifyParticipant(w http.ResponseWriter, r *http.Request, participantID ParticipantID) {
	var request VerifyParticipantRequestObject

	request.ParticipantID = participantID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyParticipant(ctx, request.(VerifyParticipantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyParticipant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyParticipantResponseObject); ok {
		if err := validResponse.VisitVerifyParticipantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FfNcts2EH4VDNqDPUOJiu1Dq5xcx50qk3Y8stwcbB0gYiUhJQFkATjDejjTh+g75D3yKH2SDgBKBCXF",
	"udjuoTfib/fbD9/ugg+0UJVWEqQ1dPxANUNWgQXcjKwohGbSTt74CQ6mQKGtUJKO6VW3TG5uJm+GNKPC",
	"L2hm1zSjklUQRqmVjCJ8dAKB07FFBxk1xRoq5s3bWvsDxqKQK9o0zWYxoLlEVBhgodKAVkCYNqVb7WO7",
	"tmxRAilKAdIOlqwQckXAWyCCg7RiKQA94F2fKb7baHy+3aUWH6CwtMnoFaqlKGEKRitpYB8WF0aXrP4t",
	"cLAXWkahYqI8uJLyxQ/uMJZZF7yAdJXHibASxoJHndF7QB8eT4B/Jby+qw2orAd+6+4QDdPWbyKFKXx0",
	"YOxTMiL4/gVfxJtdgQRkFjjRB9T4ePTiayHvR+pJh8KhsPW1V2SMaAEMAc+dXXejnxVWzNIxfft+Rlv9",
	"ektxtcO0tlZHiQu5VPvxRWaR+SFhkpN4q0WcUEvCXBE+k7gNOeKqMPn59OKXyezyYnYzvRxWnHz5fDI8",
	"zciXzz8cD4mH6xOgCKyhchYMYQikUk76KSc5ILFrIDnTgqxQOf2aYIpHGKLdohQFObqjvZXJdTgJ0mJ9",
	"R48DcmH8HMJSJV6UDBtRKRtBYEYWUDBnICwUqqqUTCAQkEuFBRjy9v3MH4d7wDqeHd5Jz6ywpaf2V1Uq",
	"29PD+dUk5oWJ5L4ajryulAbJtKBjejocDU9pFipXuNo8pTVoWUVN75TAyAJIrpWQNiNSEdYRLJQcktka",
	"9sTpOSl2FPx6G7cnDcE6lMYbXDgjJBhDOLOM/PPX3+RkdEY+CbsmjBRKWm+mVJ00gh2EmBaxUEWGfDqG",
	"Xb6wHEretjyDsT8pXvt4W/v+k2ldtlHlH4yP/yEp3t8jLOmYfpd3HSVvq3f+SJlo+lnpW0KYiHU1UH8y",
	"Onu8+XTVzyf9GhhvG9hFS867lpx9MzfTdxvGOiu969oQSB/tVE1Gz0ajJyMs9rpgto9XyHtWCj4IZYvk",
	"ZDNOEA8ETxbaujYIzTig/PH5UQZ0A8v+ANmrnXR8O8+ocVXFsE4USBiR8CmlPRzrJWH+0HtINB7cCkIE",
	"fVknymi7dEjs7mFzeziqbkvef7I08z1BPt1N7z4kDrC5W0C2inxp0fVFFt2/en73TvqSqlD8Ca3Ts+d3",
	"msYqlR0slZM8ijmRL+OEHbqbb8s3T/t52mD6Yv7d76r7FfqJtfyN4rp5Tf6P5Xb6/E63t24GSpb1fy3z",
	"F+oTrERgvB5s/1j6+RXFv5NhRx1VBFUJx+2PYtdi+g/z23kzb/4NAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
