// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package ports

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// AuctionCard defines model for AuctionCard.
type AuctionCard struct {
	AuctionId           openapi_types.UUID  `json:"auctionId"`
	BidCount            int                 `json:"bidCount"`
	Currency            string              `json:"currency"`
	CurrentPriceMinor   int64               `json:"currentPriceMinor"`
	Description         string              `json:"description"`
	EndsAt              time.Time           `json:"endsAt"`
	ExtensionsUsed      int                 `json:"extensionsUsed"`
	HasReserve          bool                `json:"hasReserve"`
	IncrementMinor      int64               `json:"incrementMinor"`
	LeaderId            *openapi_types.UUID `json:"leaderId,omitempty"`
	MinimalNextBidMinor int64               `json:"minimalNextBidMinor"`
	Outcome             *string             `json:"outcome,omitempty"`
	RecentBids          []BidView           `json:"recentBids"`
	SellerId            openapi_types.UUID  `json:"sellerId"`
	StartPriceMinor     int64               `json:"startPriceMinor"`
	StartsAt            time.Time           `json:"startsAt"`
	Status              string              `json:"status"`
	Title               string              `json:"title"`
}

// BidHistoryPage defines model for BidHistoryPage.
type BidHistoryPage struct {
	Items []BidView `json:"items"`
	Page  int       `json:"page"`
	Total int       `json:"total"`
}

// BidView defines model for BidView.
type BidView struct {
	AmountMinor       int64              `json:"amountMinor"`
	BidId             openapi_types.UUID `json:"bidId"`
	BidderDisplayName string             `json:"bidderDisplayName"`
	PlacedAt          time.Time          `json:"placedAt"`
}

// CatalogItem defines model for CatalogItem.
type CatalogItem struct {
	AuctionId           openapi_types.UUID `json:"auctionId"`
	BidCount            int                `json:"bidCount"`
	Currency            string             `json:"currency"`
	CurrentPriceMinor   int64              `json:"currentPriceMinor"`
	EndingSoon          bool               `json:"endingSoon"`
	EndsAt              time.Time          `json:"endsAt"`
	MinimalNextBidMinor int64              `json:"minimalNextBidMinor"`
	SellerId            openapi_types.UUID `json:"sellerId"`
	Title               string             `json:"title"`
}

// CatalogPage defines model for CatalogPage.
type CatalogPage struct {
	Items []CatalogItem `json:"items"`
	Page  int           `json:"page"`
	Total int           `json:"total"`
}

// Dashboard defines model for Dashboard.
type Dashboard struct {
	ActiveCount    int             `json:"activeCount"`
	Currency       string          `json:"currency"`
	Items          []DashboardItem `json:"items"`
	SoldTotalMinor int64           `json:"soldTotalMinor"`
}

// DashboardItem defines model for DashboardItem.
type DashboardItem struct {
	AuctionId        openapi_types.UUID `json:"auctionId"`
	BidCount         int                `json:"bidCount"`
	EndsAt           time.Time          `json:"endsAt"`
	HammerPriceMinor int64              `json:"hammerPriceMinor"`
	Outcome          *string            `json:"outcome,omitempty"`
	SettlementStatus *string            `json:"settlementStatus,omitempty"`
	Status           string             `json:"status"`
	Title            string             `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Slug string `json:"slug"`
}

// ListAuctionRequest defines model for ListAuctionRequest.
type ListAuctionRequest struct {
	Currency       string             `json:"currency"`
	Description    *string            `json:"description,omitempty"`
	EndsAt         time.Time          `json:"endsAt"`
	Id             openapi_types.UUID `json:"id"`
	IncrementMinor int64              `json:"incrementMinor"`

	// ReservePriceMinor Omit for no reserve; never exposed in reads.
	ReservePriceMinor *int64    `json:"reservePriceMinor,omitempty"`
	StartPriceMinor   int64     `json:"startPriceMinor"`
	StartsAt          time.Time `json:"startsAt"`
	Title             string    `json:"title"`
}

// PlaceBidRequest defines model for PlaceBidRequest.
type PlaceBidRequest struct {
	AmountMinor int64              `json:"amountMinor"`
	BidId       openapi_types.UUID `json:"bidId"`
	Currency    string             `json:"currency"`
}

// AuctionID defines model for AuctionID.
type AuctionID = openapi_types.UUID

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ActiveAuctionsCatalogParams defines parameters for ActiveAuctionsCatalog.
type ActiveAuctionsCatalogParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// BidHistoryParams defines parameters for BidHistory.
type BidHistoryParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListAuctionJSONRequestBody defines body for ListAuction for application/json ContentType.
type ListAuctionJSONRequestBody = ListAuctionRequest

// PlaceBidJSONRequestBody defines body for PlaceBid for application/json ContentType.
type PlaceBidJSONRequestBody = PlaceBidRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Page through the public catalog of active auctions
	// (GET /auctions)
	ActiveAuctionsCatalog(w http.ResponseWriter, r *http.Request, params ActiveAuctionsCatalogParams)
	// List a lot for bidding (id is client-generated)
	// (POST /auctions)
	ListAuction(w http.ResponseWriter, r *http.Request)
	// Public auction card
	// (GET /auctions/{auctionID})
	AuctionCard(w http.ResponseWriter, r *http.Request, auctionID AuctionID)
	// Page through the bid history of an auction
	// (GET /auctions/{auctionID}/bids)
	BidHistory(w http.ResponseWriter, r *http.Request, auctionID AuctionID, params BidHistoryParams)
	// Place a bid (bid id is client-generated)
	// (POST /auctions/{auctionID}/bids)
	PlaceBid(w http.ResponseWriter, r *http.Request, auctionID AuctionID)
	// Cancel a bidless listing (seller only)
	// (POST /auctions/{auctionID}/cancellation)
	CancelAuction(w http.ResponseWriter, r *http.Request, auctionID AuctionID)
	// Seller's own dashboard (the seller themselves only)
	// (GET /sellers/{sellerID}/dashboard)
	SellerDashboard(w http.ResponseWriter, r *http.Request, sellerID openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Page through the public catalog of active auctions
// (GET /auctions)
func (_ Unimplemented) ActiveAuctionsCatalog(w http.ResponseWriter, r *http.Request, params ActiveAuctionsCatalogParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List a lot for bidding (id is client-generated)
// (POST /auctions)
func (_ Unimplemented) ListAuction(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Public auction card
// (GET /auctions/{auctionID})
func (_ Unimplemented) AuctionCard(w http.ResponseWriter, r *http.Request, auctionID AuctionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Page through the bid history of an auction
// (GET /auctions/{auctionID}/bids)
func (_ Unimplemented) BidHistory(w http.ResponseWriter, r *http.Request, auctionID AuctionID, params BidHistoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Place a bid (bid id is client-generated)
// (POST /auctions/{auctionID}/bids)
func (_ Unimplemented) PlaceBid(w http.ResponseWriter, r *http.Request, auctionID AuctionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel a bidless listing (seller only)
// (POST /auctions/{auctionID}/cancellation)
func (_ Unimplemented) CancelAuction(w http.ResponseWriter, r *http.Request, auctionID AuctionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Seller's own dashboard (the seller themselves only)
// (GET /sellers/{sellerID}/dashboard)
func (_ Unimplemented) SellerDashboard(w http.ResponseWriter, r *http.Request, sellerID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ActiveAuctionsCatalog operation middleware
func (siw *ServerInterfaceWrapper) ActiveAuctionsCatalog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ActiveAuctionsCatalogParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ActiveAuctionsCatalog(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuction operation middleware
func (siw *ServerInterfaceWrapper) ListAuction(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuctionCard operation middleware
func (siw *ServerInterfaceWrapper) AuctionCard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "auctionID" -------------
	var auctionID AuctionID

	err = runtime.BindStyledParameterWithOptions("simple", "auctionID", chi.URLParam(r, "auctionID"), &auctionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "auctionID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuctionCard(w, r, auctionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BidHistory operation middleware
func (siw *ServerInterfaceWrapper) BidHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "auctionID" -------------
	var auctionID AuctionID

	err = runtime.BindStyledParameterWithOptions("simple", "auctionID", chi.URLParam(r, "auctionID"), &auctionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "auctionID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params BidHistoryParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BidHistory(w, r, auctionID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlaceBid operation middleware
func (siw *ServerInterfaceWrapper) PlaceBid(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "auctionID" -------------
	var auctionID AuctionID

	err = runtime.BindStyledParameterWithOptions("simple", "auctionID", chi.URLParam(r, "auctionID"), &auctionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "auctionID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlaceBid(w, r, auctionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelAuction operation middleware
func (siw *ServerInterfaceWrapper) CancelAuction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "auctionID" -------------
	var auctionID AuctionID

	err = runtime.BindStyledParameterWithOptions("simple", "auctionID", chi.URLParam(r, "auctionID"), &auctionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "auctionID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelAuction(w, r, auctionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SellerDashboard operation middleware
func (siw *ServerInterfaceWrapper) SellerDashboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sellerID" -------------
	var sellerID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sellerID", chi.URLParam(r, "sellerID"), &sellerID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sellerID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SellerDashboard(w, r, sellerID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auctions", wrapper.ActiveAuctionsCatalog)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auctions", wrapper.ListAuction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auctions/{auctionID}", wrapper.AuctionCard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auctions/{auctionID}/bids", wrapper.BidHistory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auctions/{auctionID}/bids", wrapper.PlaceBid)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auctions/{auctionID}/cancellation", wrapper.CancelAuction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sellers/{sellerID}/dashboard", wrapper.SellerDashboard)
	})

	return r
}

type ErrorJSONResponse Error

type ActiveAuctionsCatalogRequestObject struct {
	Params ActiveAuctionsCatalogParams
}

type ActiveAuctionsCatalogResponseObject interface {
	VisitActiveAuctionsCatalogResponse(w http.ResponseWriter) error
}

type ActiveAuctionsCatalog200JSONResponse CatalogPage

func (response ActiveAuctionsCatalog200JSONResponse) VisitActiveAuctionsCatalogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ActiveAuctionsCatalog401JSONResponse struct{ ErrorJSONResponse }

func (response ActiveAuctionsCatalog401JSONResponse) VisitActiveAuctionsCatalogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuctionRequestObject struct {
	Body *ListAuctionJSONRequestBody
}

type ListAuctionResponseObject interface {
	VisitListAuctionResponse(w http.ResponseWriter) error
}

type ListAuction204ResponseHeaders struct {
	ContentLocation *string
}

type ListAuction204Response struct {
	Headers ListAuction204ResponseHeaders
}

func (response ListAuction204Response) VisitListAuctionResponse(w http.ResponseWriter) error {
	if response.Headers.ContentLocation != nil {
		w.Header().Set("Content-Location", fmt.Sprint(*response.Headers.ContentLocation))
	}
	w.WriteHeader(204)
	return nil
}

type ListAuction400JSONResponse struct{ ErrorJSONResponse }

func (response ListAuction400JSONResponse) VisitListAuctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuction401JSONResponse Error

func (response ListAuction401JSONResponse) VisitListAuctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuctionCardRequestObject struct {
	AuctionID AuctionID `json:"auctionID"`
}

type AuctionCardResponseObject interface {
	VisitAuctionCardResponse(w http.ResponseWriter) error
}

type AuctionCard200JSONResponse AuctionCard

func (response AuctionCard200JSONResponse) VisitAuctionCardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuctionCard401JSONResponse struct{ ErrorJSONResponse }

func (response AuctionCard401JSONResponse) VisitAuctionCardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuctionCard404JSONResponse Error

func (response AuctionCard404JSONResponse) VisitAuctionCardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type BidHistoryRequestObject struct {
	AuctionID AuctionID `json:"auctionID"`
	Params    BidHistoryParams
}

type BidHistoryResponseObject interface {
	VisitBidHistoryResponse(w http.ResponseWriter) error
}

type BidHistory200JSONResponse BidHistoryPage

func (response BidHistory200JSONResponse) VisitBidHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BidHistory401JSONResponse struct{ ErrorJSONResponse }

func (response BidHistory401JSONResponse) VisitBidHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlaceBidRequestObject struct {
	AuctionID AuctionID `json:"auctionID"`
	Body      *PlaceBidJSONRequestBody
}

type PlaceBidResponseObject interface {
	VisitPlaceBidResponse(w http.ResponseWriter) error
}

type PlaceBid204ResponseHeaders struct {
	ContentLocation *string
}

type PlaceBid204Response struct {
	Headers PlaceBid204ResponseHeaders
}

func (response PlaceBid204Response) VisitPlaceBidResponse(w http.ResponseWriter) error {
	if response.Headers.ContentLocation != nil {
		w.Header().Set("Content-Location", fmt.Sprint(*response.Headers.ContentLocation))
	}
	w.WriteHeader(204)
	return nil
}

type PlaceBid400JSONResponse struct{ ErrorJSONResponse }

func (response PlaceBid400JSONResponse) VisitPlaceBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PlaceBid401JSONResponse Error

func (response PlaceBid401JSONResponse) VisitPlaceBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlaceBid403JSONResponse Error

func (response PlaceBid403JSONResponse) VisitPlaceBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PlaceBid404JSONResponse Error

func (response PlaceBid404JSONResponse) VisitPlaceBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlaceBid409JSONResponse Error

func (response PlaceBid409JSONResponse) VisitPlaceBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAuctionRequestObject struct {
	AuctionID AuctionID `json:"auctionID"`
}

type CancelAuctionResponseObject interface {
	VisitCancelAuctionResponse(w http.ResponseWriter) error
}

type CancelAuction204Response struct {
}

func (response CancelAuction204Response) VisitCancelAuctionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CancelAuction401JSONResponse struct{ ErrorJSONResponse }

func (response CancelAuction401JSONResponse) VisitCancelAuctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAuction403JSONResponse Error

func (response CancelAuction403JSONResponse) VisitCancelAuctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAuction404JSONResponse Error

func (response CancelAuction404JSONResponse) VisitCancelAuctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAuction409JSONResponse Error

func (response CancelAuction409JSONResponse) VisitCancelAuctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SellerDashboardRequestObject struct {
	SellerID openapi_types.UUID `json:"sellerID"`
}

type SellerDashboardResponseObject interface {
	VisitSellerDashboardResponse(w http.ResponseWriter) error
}

type SellerDashboard200JSONResponse Dashboard

func (response SellerDashboard200JSONResponse) VisitSellerDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SellerDashboard401JSONResponse struct{ ErrorJSONResponse }

func (response SellerDashboard401JSONResponse) VisitSellerDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SellerDashboard403JSONResponse Error

func (response SellerDashboard403JSONResponse) VisitSellerDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Page through the public catalog of active auctions
	// (GET /auctions)
	ActiveAuctionsCatalog(ctx context.Context, request ActiveAuctionsCatalogRequestObject) (ActiveAuctionsCatalogResponseObject, error)
	// List a lot for bidding (id is client-generated)
	// (POST /auctions)
	ListAuction(ctx context.Context, request ListAuctionRequestObject) (ListAuctionResponseObject, error)
	// Public auction card
	// (GET /auctions/{auctionID})
	AuctionCard(ctx context.Context, request AuctionCardRequestObject) (AuctionCardResponseObject, error)
	// Page through the bid history of an auction
	// (GET /auctions/{auctionID}/bids)
	BidHistory(ctx context.Context, request BidHistoryRequestObject) (BidHistoryResponseObject, error)
	// Place a bid (bid id is client-generated)
	// (POST /auctions/{auctionID}/bids)
	PlaceBid(ctx context.Context, request PlaceBidRequestObject) (PlaceBidResponseObject, error)
	// Cancel a bidless listing (seller only)
	// (POST /auctions/{auctionID}/cancellation)
	CancelAuction(ctx context.Context, request CancelAuctionRequestObject) (CancelAuctionResponseObject, error)
	// Seller's own dashboard (the seller themselves only)
	// (GET /sellers/{sellerID}/dashboard)
	SellerDashboard(ctx context.Context, request SellerDashboardRequestObject) (SellerDashboardResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ActiveAuctionsCatalog operation middleware
func (sh *strictHandler) ActiveAuctionsCatalog(w http.ResponseWriter, r *http.Request, params ActiveAuctionsCatalogParams) {
	var request ActiveAuctionsCatalogRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ActiveAuctionsCatalog(ctx, request.(ActiveAuctionsCatalogRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ActiveAuctionsCatalog")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ActiveAuctionsCatalogResponseObject); ok {
		if err := validResponse.VisitActiveAuctionsCatalogResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAuction operation middleware
func (sh *strictHandler) ListAuction(w http.ResponseWriter, r *http.Request) {
	var request ListAuctionRequestObject

	var body ListAuctionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuction(ctx, request.(ListAuctionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuctionResponseObject); ok {
		if err := validResponse.VisitListAuctionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuctionCard operation middleware
func (sh *strictHandler) AuctionCard(w http.ResponseWriter, r *http.Request, auctionID AuctionID) {
	var request AuctionCardRequestObject

	request.AuctionID = auctionID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuctionCard(ctx, request.(AuctionCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuctionCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuctionCardResponseObject); ok {
		if err := validResponse.VisitAuctionCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BidHistory operation middleware
func (sh *strictHandler) BidHistory(w http.ResponseWriter, r *http.Request, auctionID AuctionID, params BidHistoryParams) {
	var request BidHistoryRequestObject

	request.AuctionID = auctionID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BidHistory(ctx, request.(BidHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BidHistory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BidHistoryResponseObject); ok {
		if err := validResponse.VisitBidHistoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlaceBid operation middleware
func (sh *strictHandler) PlaceBid(w http.ResponseWriter, r *http.Request, auctionID AuctionID) {
	var request PlaceBidRequestObject

	request.AuctionID = auctionID

	var body PlaceBidJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlaceBid(ctx, request.(PlaceBidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlaceBid")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlaceBidResponseObject); ok {
		if err := validResponse.VisitPlaceBidResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelAuction operation middleware
func (sh *strictHandler) CancelAuction(w http.ResponseWriter, r *http.Request, auctionID AuctionID) {
	var request CancelAuctionRequestObject

	request.AuctionID = auctionID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelAuction(ctx, request.(CancelAuctionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelAuction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelAuctionResponseObject); ok {
		if err := validResponse.VisitCancelAuctionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SellerDashboard operation middleware
func (sh *strictHandler) SellerDashboard(w http.ResponseWriter, r *http.Request, sellerID openapi_types.UUID) {
	var request SellerDashboardRequestObject

	request.SellerID = sellerID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SellerDashboard(ctx, request.(SellerDashboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SellerDashboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SellerDashboardResponseObject); ok {
		if err := validResponse.VisitSellerDashboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fnvbts2EH8VghuwFLBjdw0GzPuUPxvWoe2Cpts+FPlAi2ebBUWq5CmNlxrYQ+wJ9yQDSVmiLNq1knjr",
	"sC9BZFLH+/O73x1PdzTTeaEVKLR0ckcLZlgOCMY/nZYZCq2eX7gHoeiEFgwXdEAVy4FOKKvXB9TA+1IY",
	"4HSCpoQBtdkCcuZenGmTM6QTWpaC0wHFZeFetmiEmtPVauVetoVWFvyp3xujjfsn0wpBofuXFYUUGXOn",
	"jd5ZrdxvzQlfGpjRCf1i1BgzCqt2FKT5UzjYzIjCCaETeiXLOYFqda1vbPY5M9z7xOgCDIqg3dpmvodp",
	"AzoV/FyXwYZqUSiEORi3mpXGgMqW0WrzaljESyMyeClUcEl9oFD4zUlzYiS0ZWVCLihuT7EljDOEIYoc",
	"UibALYKyQiv7iwWeNmTB7GuwYG4gWp9qLYEpty5UZiAHhX0MkcA4mD0dnQslciZfwS2eCd7nGF1ipnNI",
	"+spABsoJ9KEXCLn9FN7OBP9VwAf3diWOGcOW7tmClHsbZJGZ/sH3b/UKr0WGpU1ajwJlyi+rONvfRhmx",
	"fqUNwsjw+riufSnAp8PagVOUSC0oRu6oYd/Bc5SjrXhf177S03eQoXPImeA/CovaLC/ZHLrcUAPkoUgp",
	"KvHdAKNGJlNLG0EJGqz3VxK32OS16BJd7pzSB3xTwfenRQ7mQthCsuUrtiX7Csky4PuDecMFQZ3UYYOW",
	"cdFBKQedM2RSz58j5P/BagCKCzW/0q1iEDFz32pwf57txX4PoJ6IbPZnlIhAIjpoOKPx4g6IPAYpxGj7",
	"d4nhgtnFVKd7oAzFDdwXyv0cUquxzSVWS/7GGbM/GLe4JDarIzcyaqe3Ds8TfVN2wfIcTG/m2NUXWUCU",
	"vgJfbW8fDtNZ1A1Ex6xU6qZCVd8v2iGyspx/WiW/KyX1hbBYXRxew/sSLHaP2JkWj923i/2wdq/W3IQO",
	"q42p9vXq51wgmWlDlCbV9u+IghswBG4LbYEToYgBxu0xHezd2/4DHfGe4BQbqNzoZnf1qN22NIWoS9eV",
	"nAm+FU6H7NB2QHVLm9VuqXaQpeePrDQCl1eO5IMxU2AGzGmJi+bph7WWP/32hlZXdN+/+NVG7QViEa74",
	"Qs20VznEkL7UUiP5648/ScUlxA8VbpGcXj6nA3oDxga8Pj0eH4897xWgWCHohD47Hh8/8yUSF17HUSXE",
	"P8zBh8QFhK25nZ76ElLxgK2KuRfRzFXeVrOU9yWYZTNM8YU4npv4TqXM6eRpqoJtF3Ilft8QxG4rQePx",
	"YLfY641ZzNfj8aNNYuIuKTGPqZaJ98NqQE/GT7dJrFWspzsDass8Z2ZJJ9QdQHBhdDlfEFwAKcqpFBnJ",
	"qgP0jIRKT+pwus5K20Q8I1avZlxg8Uzz5aN5JVE3Vu0UQ1PCqhOXky7lVmKIFBaBkyNtCFNEcMgL7RQl",
	"BtAsnf3OK5blQAR/4kqpn7R4wefBpuELHaxpG9IZ3fk4jfeO0wOi6vxEGHHp7KqKu9QJNSdHghNhSSaF",
	"03oOykUP+BP/dp2vo7t6VLnanrvR2K+TsSmFmy2jZlJ60BSKVUyk0BoAmV/v52y3++SeCRfyi7VO3+b+",
	"0bSapiVj0ExYHhKCwf+UYTfmUwmEnAlOFmHLAYh2Gkl3LKvWmNhOsOsm58EZ9/jMvNl/3ZeWnc9ZlkGB",
	"ftz4mZKt2/3s8F9dwnRmmDGlNA4dYD6SGzBiVp0zrB3ck5Hc7m8Pr/9U8OEUpP4wrLKcfCThQ8XaJl2i",
	"22RBzsjHdQIM/UoBajOFHMYI85lz5P70LmejjKkMpKwBlM6zc7+raWUesbzt6EQq3YB/pmh0UQmI/Ezh",
	"tobPglmXLNYhSrpL83KYSX+JbiAWObuFsRD6ADIJ1vr+0PdOwXSilVxWCAu/2NFdNUW9WI14PAdMFu0r",
	"v7eZF6avO+1Px2v5D/pyfMha2piTCEu0eE9c96+2wctfWaI/KFIHhRz5Xj4EEheQW5A3YOuYRpdtH4r4",
	"mv32enW9+jsAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
